### ISSUE TITLE
Support Emacs-like three-state recenter

### ISSUE THREAD

**Issue by matklad** [kaiwood/vscode-center-editor-window#2]
In emacs, successively pressing `ctrl+l` move the caret between three states: caret at the center, caret at the top, caret at the bottom. It would be useful to have such a feature: it makes the extension more powerful, without making UI more complicated.

**Comment by kaiwood** [comment]
@matklad Here's your late christmas present: b8669cde7a9b5cbdc80ae41290484956b5686ad6, feature is published in the marketplace. It's not enabled by default, you need to set `center-editor-window.threeStateToggle` to `true`. 

As far as my Emacs memories go back, it was possible to set an explicit offset of lines when moving top or bottom, implementing this as well will be my next logical step. Anything else missing?

**Comment by matklad** [comment]
Ohhh, works flawlessly @kaiwood !!

Thank you very much!

>Anything else missing?

No, I don't remember any other features except for explicit offset.
