### ISSUE TITLE
Center won't function while in Search Mode

### ISSUE THREAD

**Issue by edmc-ss** [kaiwood/vscode-center-editor-window#8]
While searching for a pattern stepping through a file, it would be very helpful to be able to ^L to center what was found (it might not be in the center of the screen if a prior match was already centered and this instance is visible in the window)... but the window context seems to not be in the file being searched. Clicking in that window to get it to the context and typing ^L will center it... but, alas, clicking in the window resets the cursor in it... so ^L centers where ever you clicked in the window. Probably not what you intended.

Any fix? Work-around?

**Comment by kaiwood** [comment]
It took a while, but this one just got implemented.

I have to figure out why the path for the transpiled extension is currently broken (See https://github.com/kaiwood/vscode-center-editor-window/pull/5 for reference). Will prepare a release after that.
